/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErcSol from "./MyERC.sol";
export { StudentSocialDAO__factory } from "./StudentSocialDAO__factory";
