/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myErcSol from "./MyERC.sol";
export type { myErcSol };
export type { StudentSocialDAO } from "./StudentSocialDAO";
