/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentSociety } from "./StudentSociety";
export type { StudentSocietyDAO } from "./StudentSocietyDAO";
